// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: photoframe

#include "../ui.h"

lv_obj_t * ui_image_gallery = NULL;
lv_obj_t * ui_time_weather_area = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_week_month = NULL;
lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_temp = NULL;
// event funtions

// build funtions

void ui_image_gallery_screen_init(void)
{
    ui_image_gallery = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_image_gallery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time_weather_area = lv_obj_create(ui_image_gallery);
    lv_obj_remove_style_all(ui_time_weather_area);
    lv_obj_set_width(ui_time_weather_area, 315);
    lv_obj_set_height(ui_time_weather_area, 89);
    lv_obj_set_x(ui_time_weather_area, -1);
    lv_obj_set_y(ui_time_weather_area, 71);
    lv_obj_set_align(ui_time_weather_area, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_time_weather_area, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_time_weather_area, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_time_weather_area);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -80);
    lv_obj_set_y(ui_time, 20);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_SFPro55pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week_month = lv_label_create(ui_time_weather_area);
    lv_obj_set_width(ui_week_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_week_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week_month, -82);
    //lv_obj_set_x(ui_week_month, -88);
    lv_obj_set_y(ui_week_month, -20);
    lv_obj_set_align(ui_week_month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week_month, "Sat, Aug");
    lv_obj_set_style_text_color(ui_week_month, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week_month, &ui_font_SFPro25pt, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather = lv_image_create(ui_time_weather_area);
    lv_image_set_src(ui_weather, &ui_img_img_weather_1_png);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather, 71);
    lv_obj_set_y(ui_weather, 21);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weather, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp = lv_label_create(ui_time_weather_area);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 124);
    lv_obj_set_y(ui_temp, 21);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "28°");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &ui_font_SFProbold35pt, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_image_gallery_screen_destroy(void)
{
    if(ui_image_gallery) lv_obj_del(ui_image_gallery);

    // NULL screen variables
    ui_image_gallery = NULL;
    ui_time_weather_area = NULL;
    ui_time = NULL;
    ui_week_month = NULL;
    ui_weather = NULL;
    ui_temp = NULL;

}
