// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: photoframe

#ifndef UI_IMAGE_GALLERY_H
#define UI_IMAGE_GALLERY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_image_gallery
extern void ui_image_gallery_screen_init(void);
extern void ui_image_gallery_screen_destroy(void);
extern lv_obj_t * ui_image_gallery;
extern lv_obj_t * ui_time_weather_area;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_week_month;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_temp;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

