// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: photoframe

#include "../ui.h"

lv_obj_t * ui_setup = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_batt = NULL;
lv_obj_t * ui_name_header = NULL;
lv_obj_t * ui_qr_aera = NULL;
lv_obj_t * ui_ip_address = NULL;
// event funtions

// build funtions

void ui_setup_screen_init(void)
{
    ui_setup = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header = lv_obj_create(ui_setup);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_width(ui_header, 320);
    lv_obj_set_height(ui_header, 48);
    lv_obj_set_x(ui_header, 0);
    lv_obj_set_y(ui_header, -97);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_header, lv_color_hex(0xE9EAED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batt = lv_image_create(ui_header);
    lv_image_set_src(ui_batt, &ui_img_img_batt20_png);
    lv_obj_set_width(ui_batt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batt, 117);
    lv_obj_set_y(ui_batt, 0);
    lv_obj_set_align(ui_batt, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batt, 350);

    ui_name_header = lv_image_create(ui_header);
    lv_image_set_src(ui_name_header, &ui_img_img_header_png);
    lv_obj_set_width(ui_name_header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_name_header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_name_header, -73);
    lv_obj_set_y(ui_name_header, 0);
    lv_obj_set_align(ui_name_header, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_name_header, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_name_header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qr_aera = lv_obj_create(ui_setup);
    lv_obj_remove_style_all(ui_qr_aera);
    lv_obj_set_width(ui_qr_aera, 175);
    lv_obj_set_height(ui_qr_aera, 155);
    lv_obj_set_x(ui_qr_aera, 0);
    lv_obj_set_y(ui_qr_aera, 10);
    lv_obj_set_align(ui_qr_aera, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_qr_aera, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ip_address = lv_label_create(ui_setup);
    lv_obj_set_width(ui_ip_address, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ip_address, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ip_address, -8);
    lv_obj_set_y(ui_ip_address, 104);
    lv_obj_set_align(ui_ip_address, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ip_address, "PhotoFrame-Setup");
    lv_obj_set_style_text_color(ui_ip_address, lv_color_hex(0x16C1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ip_address, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ip_address, &ui_font_SFProbold19pt, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_setup_screen_destroy(void)
{
    if(ui_setup) lv_obj_del(ui_setup);

    // NULL screen variables
    ui_setup = NULL;
    ui_header = NULL;
    ui_batt = NULL;
    ui_name_header = NULL;
    ui_qr_aera = NULL;
    ui_ip_address = NULL;

}
