// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: photoframe

#ifndef UI_SETUP_H
#define UI_SETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setup
extern void ui_setup_screen_init(void);
extern void ui_setup_screen_destroy(void);
extern lv_obj_t * ui_setup;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_batt;
extern lv_obj_t * ui_name_header;
extern lv_obj_t * ui_qr_aera;
extern lv_obj_t * ui_ip_address;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

