; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ESP32-S3-WROOM-1-N16R8]
platform = espressif32
board = ESP32-S3-WROOM-1-N16R8
framework = arduino
monitor_speed = 115200
lib_extra_dirs = lib
lib_deps = 
	lovyan03/LovyanGFX@^1.2.26
	lvgl/lvgl@9.3.0
	bodmer/TJpg_Decoder@^1.1.0
	bblanchon/ArduinoJson@^7.2.2
board_build.partitions = partition/custom_partition.csv
board_build.filesystem = littlefs
board_build.spiffs_bin_name = littlefs.bin 
;build_unflags = -std=gnu++11
;build_flags = -std=gnu++17