// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: photoframe

#include "ui.h"

///////////////////// VARIABLES ////////////////////
lv_anim_t * batteryindicator_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
lv_obj_t * ui____initial_actions0;

int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a){
    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;
}

void _ui_anim_callback_free_user_data(lv_anim_t * a){
    lv_free(a->user_data);
    a->user_data = NULL;
}

void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v){

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_image_set_src(usr->target, usr->imgset[v]);
}


// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_batt[5] = {&ui_img_img_batt100_png, &ui_img_img_batt20_png, &ui_img_img_batt40_png, &ui_img_img_batt60_png, &ui_img_img_batt80_png};
const lv_image_dsc_t * ui_imgset_weather_[5] = {&ui_img_img_weather_1_png, &ui_img_img_weather_2_png, &ui_img_img_weather_3_png, &ui_img_img_weather_4_png, &ui_img_img_weather_5_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * batteryindicator_Animation(lv_obj_t * TargetObject, int delay)
{
    lv_anim_t * out_anim;
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_batt;
    PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_batt) / (sizeof(lv_image_dsc_t *));
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_duration(&PropertyAnimation_0, 800);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame);
    lv_anim_set_values(&PropertyAnimation_0, 0, 5);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_reverse_duration(&PropertyAnimation_0, 0);
    lv_anim_set_reverse_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 1);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame);
    out_anim = lv_anim_start(&PropertyAnimation_0);

    return out_anim;
}


///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_setup_screen_init();
    ui_image_gallery_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_setup);
    ui_events_init();
    
}

void ui_destroy(void)
{
    ui_setup_screen_destroy();
    ui_image_gallery_screen_destroy();
}
