// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: photoframe

#ifndef _PHOTOFRAME_UI_H
#define _PHOTOFRAME_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_setup.h"
#include "screens/ui_image_gallery.h"
#include "ui/ui_events.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * batteryindicator_Animation(lv_obj_t * TargetObject, int delay);

typedef struct _ui_anim_user_data_t {
    lv_obj_t * target;
    lv_image_dsc_t ** imgset;
    int32_t imgset_size;
    int32_t val;
} ui_anim_user_data_t;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_batt20_png);    // assets/img/batt20.png
LV_IMG_DECLARE(ui_img_img_header_png);    // assets/img/header.png
LV_IMG_DECLARE(ui_img_img_batt100_png);    // assets/img/batt100.png
LV_IMG_DECLARE(ui_img_img_batt40_png);    // assets/img/batt40.png
LV_IMG_DECLARE(ui_img_img_batt60_png);    // assets/img/batt60.png
LV_IMG_DECLARE(ui_img_img_batt80_png);    // assets/img/batt80.png
LV_IMG_DECLARE(ui_img_img_weather_1_png);    // clear.png
LV_IMG_DECLARE(ui_img_img_weather_2_png);    // cloud.png
LV_IMG_DECLARE(ui_img_img_weather_3_png);    // drizze.png
LV_IMG_DECLARE(ui_img_img_weather_4_png);    // rain.png
LV_IMG_DECLARE(ui_img_img_weather_5_png);    // thunderstorm.png

// FONTS
LV_FONT_DECLARE(ui_font_SFPro55pt);
LV_FONT_DECLARE(ui_font_SFProbold35pt);
LV_FONT_DECLARE(ui_font_SFProbold19pt);;
LV_FONT_DECLARE(ui_font_SFPro25pt);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

 #endif
